GCC = gcc
CFLAGS = -g -Wall -Wshadow
LIBS = 
SOURCES = answer06.c pa06.c
TARGET = pa06
TESTCASES := $(shell seq 1 5)

TESTS := $(addprefix test,${TESTCASES})

.PHONY : all build clean environment help testall $
